### PR TITLE
Replace deprecated functions in scipy v1.14.0

### LINKED ISSUE #255: Deprecation Scipy v1.14.0
The simps method used in ocelot is deprecated since the new scipy release v1.14.0

https://github.com/ocelot-collab/ocelot/blob/18f64f22baa9983cc5e2e259adb44ffa9e08fa6b/ocelot/cpbd/reswake.py#L4

C.f. the [release note from scipy](https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations):
> scipy.integrate.{simps,trapz,cumtrapz} have been removed in favour of simpson, trapezoid, and cumulative_trapezoid.

### PR DESCRIPTION
**Pull request by cr-xu**
Fixes #255 

Replace the deprecated functions `simps` and `cumtrapz` since the latest scipy v1.14.0 release with `simpson` and `cumulative_trapezoid`

### CODE REVIEW

**Comment by cr-xu** [comment]
The tests are passing with `scipy==1.14.0` and `numpy==1.23.5`.

While the scipy fixes are straightforward, the numpy v2.0.0 compatibility could be quite a bit more to update.

**Comment by st-walker** [comment]
Hi, thanks for the pull request.  Is this backwards compatible with older versions of scipy?  I assume it is.

**Comment by cr-xu** [comment]
> Hi, thanks for the pull request. Is this backwards compatible with older versions of scipy? I assume it is.

Yes. The functions are already renamed since `v1.6.0` which was released 2020. 

For python 3.7-3.9 scipy 1.13 will be installed, and for python>=3.10 scipy 1.14 will be installed by default.

**Comment by st-walker** [comment]
is this good to merge?  it seems the simps and simpson api for example are not the same, x is kwarg only in simpson but an arg in simps, as you commited after my comment.  is this all ok for the other functions?

**Comment by cr-xu** [comment]
> is this good to merge? it seems the simps and simpson api for example are not the same, x is kwarg only in simpson but an arg in simps, as you commited after my comment. is this all ok for the other functions?

I believe it's good to merge now. The other function `cumulative_trapezoid` doesn't require that change.

**Comment by st-walker** [comment]
Hi, I have merged it.  In future ideally we should try to send pull requests to the `dev` , but I guess on this occasion it probably makes more sense to merge a change of this kind into master as master is effectively broken for certain Python versions otherwise.

Anyway thanks again for the PR and I encourage you to continue to support ocelot in this way, if you like of course, but it would be most welcome.

**Comment by cr-xu** [comment]
Thanks for merging. I was not aware of the progress `dev` branch. Sure, I'll consider opening future PRs to the `dev` branch!

**Pull request merged**
